### ISSUE TITLE
Cannot install gm without internet access

### ISSUE THREAD

**Issue by celldara** [codership/galera-manager-support#26]
Allows for GMD Package Repository URL for local repository, but not for InfluxDB.  Continues to overwrite the influxDB repo that already exists for local repository and doesn't allow configuration for local repository

From logs

Updating Subscription Management repositories.
Galera Manager                                   59 kB/s | 2.9 kB     00:00
InfluxDB Repository - RHEL 8                    0.0  B/s |   0  B     01:52
Errors during downloading metadata for repository 'influxdb':
  - Curl error (7): Couldn't connect to server for https://repos.influxdata.com/rhel/8/x86_64/stable/repodata/repomd.xml [Failed to connect to repos.influxdata.com port 443: Connection timed out]
Error: Failed to download metadata for repo 'influxdb': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

after it overwrote our inhouse InfluxDB repository repo

**Comment by celldara** [comment]
Even if using HTTP_PROXY to get past that issue and allow for using the overwritten repo.

▊ 2022/03/02 15:19:44 INFO: Installing InfluxDB
▎ 2022/03/02 15:19:48 INFO: Installing Wget
▍ 2022/03/02 15:19:51 TRACE: requirements not met, skipping "ec2_nginx_prerequisite"
2022/03/02 15:19:51 INFO: Installing EPEL repo
2022/03/02 15:19:51 INFO: Executing: bash -c 'cd /tmp && wget -O epel.rpm -nv https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && yum install -y ./epel.rpm || yum reinstall -y ./e▃

it tries to connect to the internet to install fedoraproject EPEL instead of using the current EPEL repo that exists on our server.

**Comment by celldara** [comment]
Allowed to complete the install using http proxy, even though it installed from local repositories most of the items, gmd will not start because /etc/default/gmd does not exist to allow gmd to start ending with a failed install.

What should this file look like?  Why is it not created?

Issues before that is using default nginx.conf file which sets server to listen on port 80 for IPv4 and IPv6 (not everyone uses IPv6, especially with no internet access) without disabling this and then running gmd site on port 80, which it never gets to.

I don't understand the reasoning for creating an ELF file install for something as simple as a script that does nothing but yum installs and writes a few files.

**Comment by peter-reimann-1** [comment]
Yeah would be nice if it were possible to install gm without internet access. Escpecially for production host on premise this is a must have.

**Comment by celldara** [comment]
even allowing for full access to internet.

2022/03/03 08:55:34 DEBUG: Writing to /etc/nginx/sites-available/influxdb
2022/03/03 08:55:34 INFO: Enable Nginx InfluxDB configuration
2022/03/03 08:55:34 INFO: Executing: ln -s /etc/nginx/sites-available/influxdb /etc/nginx/sites-enabled/influxdb
2022/03/03 08:55:34 TRACE: requirements not met, skipping "initializing_gmd_db"
2022/03/03 08:55:34 TRACE: requirements not met, skipping "set_influx_dbname"
2022/03/03 08:55:34 TRACE: requirements not met, skipping "set_influx_user"
2022/03/03 08:55:34 TRACE: requirements not met, skipping "generate_influx_password"
2022/03/03 08:55:34 TRACE: requirements not met, skipping "write_gmd_service_configuration"
2022/03/03 08:55:34 TRACE: requirements not met, skipping "generate_rsa_keys"
2022/03/03 08:55:34 INFO: Fix /var/lib/gmd/jwt-rsa.* permissions
2022/03/03 08:55:34 INFO: Executing: bash -c 'chown gmd:gmd /var/lib/gmd/jwt-rsa.*'
2022/03/03 08:55:34 INFO: Enabling influxdb service
▋ 2022/03/03 08:55:36 INFO: Enabling gmd service
▊ 2022/03/03 08:55:36 INFO: Starting influxdb service
2022/03/03 08:55:36 INFO: Executing: systemctl start influxdb
2022/03/03 08:55:36 INFO: Waiting 15 seconds for influxdb to start
▊ 2022/03/03 08:55:51 TRACE: requirements not met, skipping "setup_influx_v2"
2022/03/03 08:55:51 TRACE: requirements not met, skipping "install_jq"
2022/03/03 08:55:51 TRACE: requirements not met, skipping "get_bucket_id"
2022/03/03 08:55:51 TRACE: requirements not met, skipping "setup_influx_v1_compatibility"
2022/03/03 08:55:51 TRACE: requirements not met, skipping "setup_influx_v1_compatibility_2"
2022/03/03 08:55:51 TRACE: requirements not met, skipping "backup_influxdb_yml"
2022/03/03 08:55:51 INFO: Write InfluxDB Service Configuration


and it doesn't create /etc/default/gmd so gmd is not able to start.

What requirements are not met?  Error handling here is atrocious.

**Comment by celldara** [comment]
Finally got an install to work after I pre-install nginx and commented out the listen lines before running the gm-installer
It installs, but gmd is not listening on port 8000 localhost even tho it says it is

[root@vapp-galera-manager-01 ~]# systemctl status gmd
● gmd.service - gmd - galera manager daemon
   Loaded: loaded (/usr/lib/systemd/system/gmd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2022-03-04 11:31:18 EST; 2s ago
 Main PID: 7304 (gmd)
    Tasks: 6 (limit: 23546)
   Memory: 20.8M
   CGroup: /system.slice/gmd.service
           └─7304 /usr/bin/gmd run --rsa-private-key=/var/lib/gmd/jwt-rsa.key

Mar 04 11:31:18 vapp-galera-manager-01.msc01.gdot.ad.local systemd[1]: gmd.service: Succeeded.
Mar 04 11:31:18 vapp-galera-manager-01.msc01.gdot.ad.local systemd[1]: Stopped gmd - galera manager daemon.
Mar 04 11:31:18 vapp-galera-manager-01.msc01.gdot.ad.local systemd[1]: Started gmd - galera manager daemon.
Mar 04 11:31:18 vapp-galera-manager-01.msc01.gdot.ad.local gmd[7304]: time="2022-03-04T11:31:18.970" level=info msg="Starting gmd" func="github.com/codership/galera-manager/pkg/cmd.(*RunCommand).Execu>
Mar 04 11:31:18 vapp-galera-manager-01.msc01.gdot.ad.local gmd[7304]: time="2022-03-04T11:31:18.970" level=info msg="Listening on 127.0.0.1:8000" func="github.com/codership/galera-manager/pkg/cmd.(*Ru>
Mar 04 11:31:18 vapp-galera-manager-01.msc01.gdot.ad.local gmd[7304]: time="2022-03-04T11:31:18.970" level=info msg="ConfigDir = /var/lib/gmd" func="github.com/codership/galera-manager/pkg/cmd.(*RunCo>
Mar 04 11:31:18 vapp-galera-manager-01.msc01.gdot.ad.local gmd[7304]: time="2022-03-04T11:31:18.970" level=info msg="LogsDir = /var/log/gmd" func="github.com/codership/galera-manager/pkg/cmd.(*RunComm>
[root@vapp-galera-manager-01 ~]# netstat -an | grep -w LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8086            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:46713         0.0.0.0:*               LISTEN

**Comment by celldara** [comment]
and why would the installer install certbot on a server that cannot use it or if I didn't want it.  This is bad design to force certbot, since many places don't allow it.

**Comment by denisgcm** [comment]
So, let me summarize what have here:

- [ ] Inability to install gmd without Internet
- [ ] Existing Epel repo is ignored and a new one is being tried to be installed
- [ ] `certbot` is being installed even if it's not required because of the configuration choice

Among these three items, we do not support first two ones at the moment, and it's not our priority for now.

As for the last point, this is an issue that we'll fix in one of the next releases.

---

Note, that `gm-installer` is not for advanced installations like you have. And however we currently can _only_ provide support for the installations done via `gm-installer`, you can still install `gmd` (Galera Manager Daemon) manually from the package.

For **CentOS/RedHat** installations you should create this repo:

`/etc/yum.repos.d/galera-manager.repo`

```
[galera-manager]
name = Galera Manager
baseurl = https://repo.galera-manager.com/nexus/repository/galera-manager-release
gpgcheck = 0
```

Then `yum install galera-manager`. 

For the **Debian/Ubuntu** distributions, you should create this repo:

`/etc/apt/sources.list.d/galera-manager.list`

```
deb https://repo.galera-manager.com/nexus/repository/galera-manager-release-1804 bionic main
```

Note, we currently have only Ubuntu 18.04 Bionic repository, but the package is universal for any non-EOL Ubuntu/Debian distribution, so it should not be a problem.

Then run:

```bash
apt-get update
apt-get install galera-manager
```

After the installation, you will need to set up the environment for `gmd` in `/etc/default/gmd`:

```
GMD_CONFIG_DIR=/var/lib/gmd
GMD_LOGS_DIR=/var/log/gmd
INFLUXDB_URL=https://<INFLUX_USER>:<INFLUX_PASS>@<INFLUX_ADDR>:<INFLUX_PORT>
```

Note, that we only support InfluxDB API v1 at the moment. We do already install InfluxDB 2 with the new installations, but we still use the API v1 (we are in transition to v2 currently).

After you install and configure `gmd` you need to run `systemctl stop gmd` (it shouldn't be running, but just to be sure). Then you should run:

```bash
GMD_CONFIG_DIR=/var/lib/gmd GMD_LOGS_DIR=/var/log/gmd gmd --admin-user-name=admin --admin-password=yourpassword
```

If you happen to have the DB initialized already, you can add `-f` to the flag list - this will enforce a new application database re-creation.

Then you can run `systemctl enable --now gmd`. This will make your `gmd` installation enabled during the system boot and make it running on this address: `127.0.0.1:8000`. If you want to change the port, you should add `BIND_ADDRESS=127.0.0.1:your_port` to `/etc/default/gmd` and restart the service. Note, we do not recommend exposing `gmd` directly without involving an `http` service in front of it (e.g. `nginx`).

This should be enough to start in a custom environment like you have. But we do not support it officially at the moment.
