### ISSUE TITLE
gm-installer for ubuntu 22.04

### ISSUE THREAD

**Issue by satxroadrunner** [codership/galera-manager-support#43]
I attempted to install gm-installer on Ubuntu 22.04 but received the error "unsupported os" which makes sense because Jammy came out earlier this year. What are the plans for adding 22.04 to both the manager and nodes?

**Comment by sidrob** [comment]
I have the same error
ERRO[0036] Failed to complete installation: unsupported os 

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by mattmattox** [comment]
This is still broken.

```
INFO[0000] OS Detected: Debian / Ubuntu / Linux / jammy / 22.04 
ERRO[0013] Failed to complete installation: unsupported os 
```

**Comment by satxroadrunner** [comment]
@denisgcm any updates?

**Comment by byte** [comment]
Fixed in the current installer, 1.11.0

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
./gm-installer version
gm-installer version 1.11.0 (linux/amd64)

So for the manager, you can now deploy on 22.04

For the nodes, this is still not possible

**Comment by cpt-pirx** [comment]
about when will 22.04 deploy be available for the nodes?

**Comment by satxroadrunner** [comment]
@cpt-pirx I have used 20.04 for a node and then upgraded to 22.04.. that seemed to work for me. Kind of hacky, but still.

**Comment by byte** [comment]
Fixed in current release gm-installer version 1.11.0 (linux/amd64) and Galera Manager GUI 1.8.0
